- name: Copy the /status/sinal.sh file to the /proaluno folder
  copy:
    src: files/status/sinal.sh
    dest: /proaluno/sinal.sh
    mode: '0755'

- name: Cron file to refresh the pc status (file in /etc/cron.d)
  ansible.builtin.cron:
    name: cron status
    weekday: "*"
    minute: "/5"
    hour: "*"
    user: root
    job: "sh /proaluno/sinal.sh"
    cron_file: ansible_status

- name: cron
  service:
    name: cron
    state: restarted