# Para gerar nova checksum: sha256sum authorized_keys
- name: Update SSH Authorized Keys
  get_url:
    url: http://public.fflch.usp.br/proaluno/files/authorized_keys
    dest: /root/.ssh/authorized_keys
    mode: '0600'
